### PR TITLE
Asynchronous processing

### PR DESCRIPTION
**Pull request by sharpner**
TODOs:
- [x] Nice handling of url creation
- [ ] Find a clean solution to handle subtrees e.g. /jobs/queues/1 like in the spec

### CODE REVIEW

**Comment by sharpner** [comment]
So I kinda got this to work, but the tricky part is now the correct handling.
The actual flow of asynch operations would be:
### POST /photos
Create gets called, but it does not create a photo, instead it creates a temporary handle. In the example
it creates /photos/queue-jobs/5234 that only contains a "status" attribute. 
Optionally you get a *Content-Location* Header with the optional full resource identifier.

### GET /photos/queue-jobs/5234
This call will return 303 See Other when its done. Additionally it contains a *Location* Header back to the actual Photo that got created. E.g. *Location: https://example.com/photos/4577*
No documentation as to what is if the process is not yet finished.

IMHO api2go does not yet have the functionality to implement such an behaviour. A user can probably fake it after this PR gets merged (without the optional location header) but to implement the suggestion 1:1 we would need a way to respond to Create differently than either Succeed or Error.

What do you think @wwwdata?

**Comment by sharpner** [comment]
RFC for #243

**Comment by wwwdata** [comment]
so far this looks good in my opinion

**Comment by sharpner** [comment]
so we are going to merge this for now?

**Comment by wwwdata** [comment]
It cannot hurt to merge it but we should mention something about it in the Readme as well

**Pull request closed without merging**
