### PR TITLE
Cleaner error message by renamed unexported fields

### PR DESCRIPTION
**Pull request by sharpner**
The only way to check this that I could find was to use
recover.

If anyone has an idea how to check if a field is private beforehand I would
appreciate it deeply. :/

### CODE REVIEW

**Comment by wwwdata** [comment]
hm, normally the field should not have been found right? What exactly is the problem here? It finds the private field and then tries to set a value into it?

**Comment by sharpner** [comment]
The problem is that due to the renaming flag it ignores the lookup and does not search for the field, but instead uses the name from the string and forces to set it.

**Comment by wwwdata** [comment]
ah, yes make sense so it finds the private field with the tag. So can we just check if the field is private anyway and then not set it even if it has a tag?

**Comment by sharpner** [comment]
How do you check if a field is unexported? It's impossible I read the whole fucking docu :D

**Comment by wwwdata** [comment]
we did something similar in the marshaler and checked it with
```
!field.CanInterface()
```

we cannot do that here?

**Comment by sharpner** [comment]
I swear, that's the first thing I tried :D Must have had some error somewhere else in the code previously.

**Comment by wwwdata** [comment]
ok ok, that's why we have these damn pull requests for, looki looki

**Comment by sharpner** [comment]
:+1: =)

**Comment by wwwdata** [comment]
ok if tests go through then :shipit:

**Pull request merged**
