### PR TITLE
Null tests

### PR DESCRIPTION
**Pull request by dennisfaust**
These removed some confusion for me and made it more obvious the zero value and nil relationships.

### CODE REVIEW

**Comment by sharpner** [comment]
thx for the PR! 

Could you do me a favor and squash the commits? I'll merge them afterwards

**Comment by wwwdata** [comment]
thx, was about to ask to squash too :smile:

**Comment by dennisfaust** [comment]
Squashed the commits and added one more test to verify null value overwrites are correct.

**Comment by sharpner** [comment]
ok stupid build failed because of coveralls..

**Comment by sharpner** [comment]
retest this please

**Pull request merged**
